package com.supermartijn642.rechiseled;

import com.supermartijn642.core.block.BlockProperties;
import com.supermartijn642.rechiseled.api.BaseChiselingRecipes;
import com.supermartijn642.rechiseled.api.blocks.BlockSpecification;
import com.supermartijn642.rechiseled.api.blocks.RechiseledBlockBuilder;
import com.supermartijn642.rechiseled.api.blocks.RechiseledBlockType;
import net.minecraft.block.Blocks;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;

import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Created 18/04/2023 by SuperMartijn642
 */
@SuppressWarnings("unused")
public class RechiseledBlocks {

    // Acacia planks
    private static final Supplier<BlockProperties> ACACIA_PLANKS_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.WOOD, MaterialColor.COLOR_ORANGE).destroyTime(2.0F).explosionResistance(3.0F).sound(SoundType.WOOD);
    private static final Consumer<RechiseledBlockBuilder> ACACIA_PLANKS_CONFIGURER = b -> b.properties(ACACIA_PLANKS_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.ACACIA_PLANKS).recipe(BaseChiselingRecipes.ACACIA_PLANKS);
    public static final RechiseledBlockType ACACIA_PLANKS_BEAMS = create("acacia_planks_beams", "Acacia Plank Beams").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_BRICK_PATTERN = create("acacia_planks_brick_pattern", "Acacia Plank Brick Pattern").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_BRICK_PAVING = create("acacia_planks_brick_paving", "Acacia Plank Brick Paving").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_BRICKS = create("acacia_planks_bricks", "Acacia Plank Bricks").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_CRATE = create("acacia_planks_crate", "Acacia Planks Crate").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_DIAGONAL_STRIPES = create("acacia_planks_diagonal_stripes", "Diagonal Acacia Plank Stripes").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_DIAGONAL_TILES = create("acacia_planks_diagonal_tiles", "Diagonal Acacia Plank Tiles").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_DOTTED = create("acacia_planks_dotted", "Dotted Acacia Planks").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_FLOORING = create("acacia_planks_flooring", "Acacia Plank Flooring").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_LARGE_TILES = create("acacia_planks_large_tiles", "Large Acacia Plank Tiles").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_MOSAIC = create("acacia_planks_mosaic", "Acacia Plank Mosaic").configure(ACACIA_PLANKS_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType ACACIA_PLANKS_PATTERN = create("acacia_planks_pattern", "Acacia Plank Pattern").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_ROTATED_BRICKS = create("acacia_planks_rotated_bricks", "Rotated Acacia Plank Bricks").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_SMALL_BRICKS = create("acacia_planks_small_bricks", "Small Acacia Plank Bricks").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_SMALL_TILES = create("acacia_planks_small_tiles", "Small Acacia Plank Tiles").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_SQUARES = create("acacia_planks_squares", "Acacia Plank Squares").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_TILES = create("acacia_planks_tiles", "Acacia Plank Tiles").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_WAVY = create("acacia_planks_wavy", "Wavy Acacia Planks").configure(ACACIA_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType ACACIA_PLANKS_WOVEN = create("acacia_planks_woven", "Woven Acacia Planks").configure(ACACIA_PLANKS_CONFIGURER).build();
    // Andesite
    private static final Supplier<BlockProperties> ANDESITE_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.STONE).requiresCorrectTool().destroyTime(1.5F).explosionResistance(6.0F);
    private static final Consumer<RechiseledBlockBuilder> ANDESITE_CONFIGURER = b -> b.properties(ANDESITE_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.POLISHED_ANDESITE).recipe(BaseChiselingRecipes.ANDESITE);
    public static final RechiseledBlockType ANDESITE_BRICK_PATTERN = create("andesite_brick_pattern", "Andesite Brick Pattern").configure(ANDESITE_CONFIGURER).build();
    public static final RechiseledBlockType ANDESITE_BRICK_PAVING = create("andesite_brick_paving", "Andesite Brick Paving").configure(ANDESITE_CONFIGURER).build();
    public static final RechiseledBlockType ANDESITE_BRICKS = create("andesite_bricks", "Andesite Bricks").configure(ANDESITE_CONFIGURER).build();
    public static final RechiseledBlockType ANDESITE_DIAGONAL_BRICKS = create("andesite_diagonal_bricks", "Diagonal Andesite Bricks").configure(ANDESITE_CONFIGURER).build();
    public static final RechiseledBlockType ANDESITE_DOTTED = create("andesite_dotted", "Dotted Andesite").configure(ANDESITE_CONFIGURER).build();
    public static final RechiseledBlockType ANDESITE_PAVING = create("andesite_paving", "Andesite Paving").configure(ANDESITE_CONFIGURER).build();
    public static final RechiseledBlockType ANDESITE_POLISHED = create("andesite_polished", "Polished Andesite").configure(ANDESITE_CONFIGURER).regularVariant(() -> Blocks.POLISHED_ANDESITE).build();
    public static final RechiseledBlockType ANDESITE_ROTATED_BRICKS = create("andesite_rotated_bricks", "Rotated Andesite Bricks").configure(ANDESITE_CONFIGURER).build();
    public static final RechiseledBlockType ANDESITE_SQUARES = create("andesite_squares", "Andesite Squares").configure(ANDESITE_CONFIGURER).build();
    public static final RechiseledBlockType ANDESITE_TILES = create("andesite_tiles", "Andesite Tiles").configure(ANDESITE_CONFIGURER).build();
    public static final RechiseledBlockType ANDESITE_WAVY = create("andesite_wavy", "Wavy Andesite").configure(ANDESITE_CONFIGURER).build();
    // Birch planks
    private static final Supplier<BlockProperties> BIRCH_PLANKS_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.WOOD, MaterialColor.SAND).destroyTime(2.0F).explosionResistance(3.0F).sound(SoundType.WOOD);
    private static final Consumer<RechiseledBlockBuilder> BIRCH_PLANKS_CONFIGURER = b -> b.properties(BIRCH_PLANKS_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.BIRCH_PLANKS).recipe(BaseChiselingRecipes.BIRCH_PLANKS);
    public static final RechiseledBlockType BIRCH_PLANKS_BEAMS = create("birch_planks_beams", "Birch Plank Beams").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_BRICK_PATTERN = create("birch_planks_brick_pattern", "Birch Plank Brick Pattern").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_BRICK_PAVING = create("birch_planks_brick_paving", "Birch Plank Brick Paving").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_BRICKS = create("birch_planks_bricks", "Birch Plank Bricks").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_CRATE = create("birch_planks_crate", "Birch Planks Crate").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_DIAGONAL_STRIPES = create("birch_planks_diagonal_stripes", "Diagonal Birch Plank Stripes").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_DIAGONAL_TILES = create("birch_planks_diagonal_tiles", "Diagonal Birch Plank Tiles").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_DOTTED = create("birch_planks_dotted", "Dotted Birch Planks").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_FLOORING = create("birch_planks_flooring", "Birch Plank Flooring").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_LARGE_TILES = create("birch_planks_large_tiles", "Large Birch Plank Tiles").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_MOSAIC = create("birch_planks_mosaic", "Birch Plank Mosaic").configure(BIRCH_PLANKS_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType BIRCH_PLANKS_PATTERN = create("birch_planks_pattern", "Birch Plank Pattern").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_ROTATED_BRICKS = create("birch_planks_rotated_bricks", "Rotated Birch Plank Bricks").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_SMALL_BRICKS = create("birch_planks_small_bricks", "Small Birch Plank Bricks").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_SMALL_TILES = create("birch_planks_small_tiles", "Small Birch Plank Tiles").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_SQUARES = create("birch_planks_squares", "Birch Plank Squares").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_TILES = create("birch_planks_tiles", "Birch Plank Tiles").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_WAVY = create("birch_planks_wavy", "Wavy Birch Planks").configure(BIRCH_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType BIRCH_PLANKS_WOVEN = create("birch_planks_woven", "Woven Birch Planks").configure(BIRCH_PLANKS_CONFIGURER).build();
    // Blue ice
    private static final Supplier<BlockProperties> BLUE_ICE_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.ICE_SOLID).strength(2.8F).friction(0.989F).sound(SoundType.GLASS);
    private static final Consumer<RechiseledBlockBuilder> BLUE_ICE_CONFIGURER = b -> b.properties(BLUE_ICE_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.BLUE_ICE).recipe(BaseChiselingRecipes.BLUE_ICE);
    public static final RechiseledBlockType BLUE_ICE_BORDERED = create("blue_ice_bordered", "Bordered Blue Ice").configure(BLUE_ICE_CONFIGURER).build();
    public static final RechiseledBlockType BLUE_ICE_BRICKS = create("blue_ice_bricks", "Blue Ice Bricks").configure(BLUE_ICE_CONFIGURER).build();
    public static final RechiseledBlockType BLUE_ICE_CHISELED = create("blue_ice_chiseled", "Chiseled Blue Ice").configure(BLUE_ICE_CONFIGURER).build();
    public static final RechiseledBlockType BLUE_ICE_CONE = create("blue_ice_cone", "Blue Ice Cone").configure(BLUE_ICE_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType BLUE_ICE_CRACKED = create("blue_ice_cracked", "Cracked Blue Ice").configure(BLUE_ICE_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType BLUE_ICE_PATTERNED = create("blue_ice_patterned", "Patterned Blue Ice").configure(BLUE_ICE_CONFIGURER).build();
    public static final RechiseledBlockType BLUE_ICE_PILLAR = create("blue_ice_pillar", "Blue Ice Pillar").configure(BLUE_ICE_CONFIGURER).specification(BlockSpecification.PILLAR).build();
    public static final RechiseledBlockType BLUE_ICE_ROCKY = create("blue_ice_rocky", "Rocky Blue Ice").configure(BLUE_ICE_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType BLUE_ICE_SLANTED_TILES = create("blue_ice_slanted_tiles", "Slanted Blue Ice Tiles").configure(BLUE_ICE_CONFIGURER).build();
    public static final RechiseledBlockType BLUE_ICE_TILES = create("blue_ice_tiles", "Blue Ice Tiles").configure(BLUE_ICE_CONFIGURER).build();
    // Bone block
    private static final Supplier<BlockProperties> BONE_BLOCK_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.SAND).requiresCorrectTool().strength(2.0F).sound(SoundType.BONE_BLOCK);
    private static final Consumer<RechiseledBlockBuilder> BONE_BLOCK_CONFIGURER = b -> b.properties(BONE_BLOCK_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.BONE_BLOCK).recipe(BaseChiselingRecipes.BONE_BLOCK);
    public static final RechiseledBlockType BONE_BLOCK_BORDERED = create("bone_block_bordered", "Bordered Bone Block").configure(BONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType BONE_BLOCK_BUNDLED = create("bone_block_bundled", "Bundled Bone Block").configure(BONE_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType BONE_BLOCK_CHISELED = create("bone_block_chiseled", "Chiseled Bone Block").configure(BONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType BONE_BLOCK_CONNECTING = create("bone_block_connecting", "Bone Block").configure(BONE_BLOCK_CONFIGURER).specification(BlockSpecification.PILLAR).regularVariant(() -> Blocks.BONE_BLOCK).build();
    public static final RechiseledBlockType BONE_BLOCK_CRACKED = create("bone_block_cracked", "Cracked Bone Block").configure(BONE_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType BONE_BLOCK_DECORATED = create("bone_block_decorated", "Decorated Bone Block").configure(BONE_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType BONE_BLOCK_DECORATED_BORDERED = create("bone_block_decorated_bordered", "Bordered Decorated Bone Block").configure(BONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType BONE_BLOCK_INVERTED_TILES = create("bone_block_inverted_tiles", "Inverted Bone Block Tiles").configure(BONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType BONE_BLOCK_PATTERNED = create("bone_block_patterned", "Patterned Bone Block").configure(BONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType BONE_BLOCK_PILLAR = create("bone_block_pillar", "Bone Block Pillar").configure(BONE_BLOCK_CONFIGURER).specification(BlockSpecification.PILLAR).build();
    public static final RechiseledBlockType BONE_BLOCK_RIB = create("bone_block_rib", "Bone Block Ribs").configure(BONE_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType BONE_BLOCK_SKULL = create("bone_block_skull", "Bone Block Skull").configure(BONE_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType BONE_BLOCK_SMOOTH = create("bone_block_smooth", "Smooth Bone Block").configure(BONE_BLOCK_CONFIGURER).noConnectingVariant().build();
    // Coal block
    private static final Supplier<BlockProperties> COAL_BLOCK_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.COLOR_BLACK).requiresCorrectTool().destroyTime(5.0F).explosionResistance(6.0F);
    private static final Consumer<RechiseledBlockBuilder> COAL_BLOCK_CONFIGURER = b -> b.properties(COAL_BLOCK_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.COAL_BLOCK).recipe(BaseChiselingRecipes.COAL_BLOCK);
    public static final RechiseledBlockType COAL_BLOCK_CARVED = create("coal_block_carved", "Carved Block of Coal").configure(COAL_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType COAL_BLOCK_CHISELED = create("coal_block_chiseled", "Chiseled Block of Coal").configure(COAL_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType COAL_BLOCK_CIRCLES = create("coal_block_circles", "Coal Block Circles").configure(COAL_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType COAL_BLOCK_COMPACTED = create("coal_block_compacted", "Compacted Block of Coal").configure(COAL_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType COAL_BLOCK_OVALS = create("coal_block_ovals", "Coal Block Ovals").configure(COAL_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType COAL_BLOCK_PATTERN = create("coal_block_pattern", "Coal Block Pattern").configure(COAL_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType COAL_BLOCK_PILLAR = create("coal_block_pillar", "Coal Block Pillar").configure(COAL_BLOCK_CONFIGURER).specification(BlockSpecification.PILLAR).build();
    public static final RechiseledBlockType COAL_BLOCK_POLISHED = create("coal_block_polished", "Polished Block of Coal").configure(COAL_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType COAL_BLOCK_ROTATED_BRICKS = create("coal_block_rotated_bricks", "Rotated Coal Bricks").configure(COAL_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType COAL_BLOCK_SMALL_TILES = create("coal_block_small_tiles", "Small Coal Block Tiles").configure(COAL_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType COAL_BLOCK_STRIPES = create("coal_block_stripes", "Coal Block Stripes").configure(COAL_BLOCK_CONFIGURER).build();
    // Cobblestone
    private static final Supplier<BlockProperties> COBBLESTONE_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE).requiresCorrectTool().destroyTime(2.0F).explosionResistance(6.0F);
    private static final Consumer<RechiseledBlockBuilder> COBBLESTONE_CONFIGURER = b -> b.properties(COBBLESTONE_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.COBBLESTONE).recipe(BaseChiselingRecipes.COBBLESTONE);
    public static final RechiseledBlockType COBBLESTONE_BEAMS = create("cobblestone_beams", "Cobblestone Beams").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_BRICK_PATTERN = create("cobblestone_brick_pattern", "Cobblestone Brick Pattern").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_BRICK_PAVING = create("cobblestone_brick_paving", "Cobblestone Brick Paving").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_CHISELED_BORDER = create("cobblestone_chiseled_border", "Chiseled Bordered Cobblestone").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_CROSSES = create("cobblestone_crosses", "Cobblestone Crosses").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_DENTED = create("cobblestone_dented", "Dented Cobblestone").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_INVERTED_DENTED = create("cobblestone_inverted_dented", "Inverted Dented Cobblestone").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_LARGE_SQUARES = create("cobblestone_large_squares", "Large Cobblestone Squares").configure(COBBLESTONE_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType COBBLESTONE_PAVING = create("cobblestone_paving", "Cobblestone Paving").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_PILLAR = create("cobblestone_pillar", "Cobblestone Pillar").configure(COBBLESTONE_CONFIGURER).specification(BlockSpecification.PILLAR).build();
    public static final RechiseledBlockType COBBLESTONE_POLISHED = create("cobblestone_polished", "Polished Cobblestone").configure(COBBLESTONE_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType COBBLESTONE_PULVERIZED = create("cobblestone_pulverized", "Pulverized Cobblestone").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_ROTATED_BRICKS = create("cobblestone_rotated_bricks", "Rotated Cobblestone Bricks").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_SHEARED = create("cobblestone_sheared", "Sheared Cobblestone").configure(COBBLESTONE_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType COBBLESTONE_SMALL_TILES = create("cobblestone_small_tiles", "Small Cobblestone Tiles").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_SQUARES = create("cobblestone_squares", "Cobblestone Squares").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_STRIPES = create("cobblestone_stripes", "Cobblestone Stripes").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_TILES = create("cobblestone_tiles", "Cobblestone Tiles").configure(COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType COBBLESTONE_WORN_STRIPES = create("cobblestone_worn_stripes", "Weathered Cobblestone Stripes").configure(COBBLESTONE_CONFIGURER).build();
    // Dark oak planks
    private static final Supplier<BlockProperties> DARK_OAK_PLANKS_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.WOOD, MaterialColor.COLOR_BROWN).destroyTime(2.0F).explosionResistance(3.0F).sound(SoundType.WOOD);
    private static final Consumer<RechiseledBlockBuilder> DARK_OAK_PLANKS_CONFIGURER = b -> b.properties(DARK_OAK_PLANKS_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.DARK_OAK_PLANKS).recipe(BaseChiselingRecipes.DARK_OAK_PLANKS);
    public static final RechiseledBlockType DARK_OAK_PLANKS_BEAMS = create("dark_oak_planks_beams", "Dark Oak Plank Beams").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_BRICK_PATTERN = create("dark_oak_planks_brick_pattern", "Dark Oak Plank Brick Pattern").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_BRICK_PAVING = create("dark_oak_planks_brick_paving", "Dark Oak Plank Brick Paving").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_BRICKS = create("dark_oak_planks_bricks", "Dark Oak Plank Bricks").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_CRATE = create("dark_oak_planks_crate", "Dark Oak Planks Crate").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_DIAGONAL_STRIPES = create("dark_oak_planks_diagonal_stripes", "Diagonal Dark Oak Plank Stripes").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_DIAGONAL_TILES = create("dark_oak_planks_diagonal_tiles", "Diagonal Dark Oak Plank Tiles").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_DOTTED = create("dark_oak_planks_dotted", "Dotted Dark Oak Planks").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_FLOORING = create("dark_oak_planks_flooring", "Dark Oak Plank Flooring").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_LARGE_TILES = create("dark_oak_planks_large_tiles", "Large Dark Oak Plank Tiles").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_MOSAIC = create("dark_oak_planks_mosaic", "Dark Oak Plank Mosaic").configure(DARK_OAK_PLANKS_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_PATTERN = create("dark_oak_planks_pattern", "Dark Oak Plank Pattern").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_ROTATED_BRICKS = create("dark_oak_planks_rotated_bricks", "Rotated Dark Oak Plank Bricks").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_SMALL_BRICKS = create("dark_oak_planks_small_bricks", "Small Dark Oak Plank Bricks").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_SMALL_TILES = create("dark_oak_planks_small_tiles", "Small Dark Oak Plank Tiles").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_SQUARES = create("dark_oak_planks_squares", "Dark Oak Plank Squares").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_TILES = create("dark_oak_planks_tiles", "Dark Oak Plank Tiles").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_WAVY = create("dark_oak_planks_wavy", "Wavy Dark Oak Planks").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType DARK_OAK_PLANKS_WOVEN = create("dark_oak_planks_woven", "Woven Dark Oak Planks").configure(DARK_OAK_PLANKS_CONFIGURER).build();
    // Dark prismarine
    private static final Supplier<BlockProperties> DARK_PRISMARINE_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.DIAMOND).requiresCorrectTool().destroyTime(1.5F).explosionResistance(6.0F);
    private static final Consumer<RechiseledBlockBuilder> DARK_PRISMARINE_CONFIGURER = b -> b.properties(DARK_PRISMARINE_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.DARK_PRISMARINE).recipe(BaseChiselingRecipes.DARK_PRISMARINE);
    public static final RechiseledBlockType DARK_PRISMARINE_BEAMS = create("dark_prismarine_beams", "Dark Prismarine Beams").configure(DARK_PRISMARINE_CONFIGURER).build();
    public static final RechiseledBlockType DARK_PRISMARINE_BRICK_PAVING = create("dark_prismarine_brick_paving", "Dark Prismarine Brick Paving").configure(DARK_PRISMARINE_CONFIGURER).build();
    public static final RechiseledBlockType DARK_PRISMARINE_BRICKS = create("dark_prismarine_bricks", "Dark Prismarine Bricks").configure(DARK_PRISMARINE_CONFIGURER).build();
    public static final RechiseledBlockType DARK_PRISMARINE_DOTTED = create("dark_prismarine_dotted", "Dotted Dark Prismarine").configure(DARK_PRISMARINE_CONFIGURER).build();
    public static final RechiseledBlockType DARK_PRISMARINE_FABRIC = create("dark_prismarine_fabric", "Dark Prismarine Fabric").configure(DARK_PRISMARINE_CONFIGURER).build();
    public static final RechiseledBlockType DARK_PRISMARINE_LARGE_TILES = create("dark_prismarine_large_tiles", "Large Dark Prismarine Tiles").configure(DARK_PRISMARINE_CONFIGURER).build();
    public static final RechiseledBlockType DARK_PRISMARINE_ROTATED_BRICKS = create("dark_prismarine_rotated_bricks", "Rotated Dark Prismarine Bricks").configure(DARK_PRISMARINE_CONFIGURER).build();
    public static final RechiseledBlockType DARK_PRISMARINE_ROWS = create("dark_prismarine_rows", "Dark Prismarine Rows").configure(DARK_PRISMARINE_CONFIGURER).build();
    public static final RechiseledBlockType DARK_PRISMARINE_SQUARES = create("dark_prismarine_squares", "Dark Prismarine Squares").configure(DARK_PRISMARINE_CONFIGURER).build();
    public static final RechiseledBlockType DARK_PRISMARINE_TILES = create("dark_prismarine_tiles", "Dark Prismarine Tiles").configure(DARK_PRISMARINE_CONFIGURER).build();
    public static final RechiseledBlockType DARK_PRISMARINE_WAVY = create("dark_prismarine_wavy", "Wavy Dark Prismarine").configure(DARK_PRISMARINE_CONFIGURER).build();
    public static final RechiseledBlockType DARK_PRISMARINE_WOVEN = create("dark_prismarine_woven", "Woven Dark Prismarine").configure(DARK_PRISMARINE_CONFIGURER).build();
    // Diamond block
    private static final Supplier<BlockProperties> DIAMOND_BLOCK_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.METAL, MaterialColor.DIAMOND).requiresCorrectTool().destroyTime(5.0F).explosionResistance(6.0F).sound(SoundType.METAL);
    private static final Consumer<RechiseledBlockBuilder> DIAMOND_BLOCK_CONFIGURER = b -> b.properties(DIAMOND_BLOCK_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.DIAMOND_BLOCK).recipe(BaseChiselingRecipes.DIAMOND_BLOCK);
    public static final RechiseledBlockType DIAMOND_BLOCK_CHISELED = create("diamond_block_chiseled", "Chiseled Block of Diamond").configure(DIAMOND_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType DIAMOND_BLOCK_CHISELED_CUBES = create("diamond_block_chiseled_cubes", "Chiseled Diamond Block Cubes").configure(DIAMOND_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType DIAMOND_BLOCK_CONNECTING = create("diamond_block_connecting", "Block of Diamonds").configure(DIAMOND_BLOCK_CONFIGURER).regularVariant(() -> Blocks.DIAMOND_BLOCK).build();
    public static final RechiseledBlockType DIAMOND_BLOCK_DIAGONAL_TILES = create("diamond_block_diagonal_tiles", "Diagonal Diamond Tiles").configure(DIAMOND_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType DIAMOND_BLOCK_GRID = create("diamond_block_grid", "Diamond Grid Block").configure(DIAMOND_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType DIAMOND_BLOCK_JEWEL_BLOCK = create("diamond_block_jewel_block", "Diamond Jewel Block").configure(DIAMOND_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType DIAMOND_BLOCK_POLISHED = create("diamond_block_polished", "Polished Block of Diamond").configure(DIAMOND_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType DIAMOND_BLOCK_RHOMBUSES = create("diamond_block_rhombuses", "Diamond Block Rhombuses").configure(DIAMOND_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType DIAMOND_BLOCK_SHINY = create("diamond_block_shiny", "Shiny Block of Diamond").configure(DIAMOND_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType DIAMOND_BLOCK_SHINY_BORDERED = create("diamond_block_shiny_bordered", "Bordered Shiny Block of Diamond").configure(DIAMOND_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType DIAMOND_BLOCK_SMALL_TILES = create("diamond_block_small_tiles", "Small Diamond Tiles").configure(DIAMOND_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType DIAMOND_BLOCK_SMOOTH = create("diamond_block_smooth", "Smooth Block of Diamond").configure(DIAMOND_BLOCK_CONFIGURER).noConnectingVariant().build();
    // Diorite
    private static final Supplier<BlockProperties> DIORITE_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.QUARTZ).requiresCorrectTool().destroyTime(1.5F).explosionResistance(6.0F);
    private static final Consumer<RechiseledBlockBuilder> DIORITE_CONFIGURER = b -> b.properties(DIORITE_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.POLISHED_DIORITE).recipe(BaseChiselingRecipes.DIORITE);
    public static final RechiseledBlockType DIORITE_BRICK_PATTERN = create("diorite_brick_pattern", "Diorite Brick Pattern").configure(DIORITE_CONFIGURER).build();
    public static final RechiseledBlockType DIORITE_BRICK_PAVING = create("diorite_brick_paving", "Diorite Brick Paving").configure(DIORITE_CONFIGURER).build();
    public static final RechiseledBlockType DIORITE_BRICKS = create("diorite_bricks", "Diorite Bricks").configure(DIORITE_CONFIGURER).build();
    public static final RechiseledBlockType DIORITE_DIAGONAL_BRICKS = create("diorite_diagonal_bricks", "Diagonal Diorite Bricks").configure(DIORITE_CONFIGURER).build();
    public static final RechiseledBlockType DIORITE_DOTTED = create("diorite_dotted", "Dotted Diorite").configure(DIORITE_CONFIGURER).build();
    public static final RechiseledBlockType DIORITE_PAVING = create("diorite_paving", "Diorite Paving").configure(DIORITE_CONFIGURER).build();
    public static final RechiseledBlockType DIORITE_POLISHED = create("diorite_polished", "Polished Diorite").configure(DIORITE_CONFIGURER).regularVariant(() -> Blocks.POLISHED_DIORITE).build();
    public static final RechiseledBlockType DIORITE_ROTATED_BRICKS = create("diorite_rotated_bricks", "Rotated Diorite Bricks").configure(DIORITE_CONFIGURER).build();
    public static final RechiseledBlockType DIORITE_SQUARES = create("diorite_squares", "Diorite Squares").configure(DIORITE_CONFIGURER).build();
    public static final RechiseledBlockType DIORITE_TILES = create("diorite_tiles", "Diorite Tiles").configure(DIORITE_CONFIGURER).build();
    public static final RechiseledBlockType DIORITE_WAVY = create("diorite_wavy", "Wavy Diorite").configure(DIORITE_CONFIGURER).build();
    // Dirt
    private static final Supplier<BlockProperties> DIRT_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.DIRT, MaterialColor.DIRT).strength(0.5F).sound(SoundType.GRAVEL);
    private static final Consumer<RechiseledBlockBuilder> DIRT_CONFIGURER = b -> b.properties(DIRT_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.DIRT).recipe(BaseChiselingRecipes.DIRT);
    public static final RechiseledBlockType DIRT_BLOBS = create("dirt_blobs", "Dirt Blobs").configure(DIRT_CONFIGURER).build();
    public static final RechiseledBlockType DIRT_BRICKS = create("dirt_bricks", "Dirt Bricks").configure(DIRT_CONFIGURER).build();
    public static final RechiseledBlockType DIRT_CHUNKS = create("dirt_chunks", "Dirt Chunks").configure(DIRT_CONFIGURER).build();
    public static final RechiseledBlockType DIRT_CLUMPS = create("dirt_clumps", "Dirt Clumps").configure(DIRT_CONFIGURER).build();
    public static final RechiseledBlockType DIRT_COBBLED = create("dirt_cobbled", "Cobbled Dirt").configure(DIRT_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType DIRT_GROOVES = create("dirt_grooves", "Dirt Grooves").configure(DIRT_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType DIRT_LARGE_TILES = create("dirt_large_tiles", "Large Dirt Tiles").configure(DIRT_CONFIGURER).build();
    public static final RechiseledBlockType DIRT_MUDDY = create("dirt_muddy", "Muddy Dirt").configure(DIRT_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType DIRT_SMALL_BRICKS = create("dirt_small_bricks", "Small Dirt Bricks").configure(DIRT_CONFIGURER).build();
    public static final RechiseledBlockType DIRT_SMALL_TILES = create("dirt_small_tiles", "Small Dirt Tiles").configure(DIRT_CONFIGURER).build();
    public static final RechiseledBlockType DIRT_SMOOTH_CLUMPS = create("dirt_smooth_clumps", "Smooth Dirt Clumps").configure(DIRT_CONFIGURER).build();
    public static final RechiseledBlockType DIRT_SOIL = create("dirt_soil", "Dirt Soil").configure(DIRT_CONFIGURER).build();
    public static final RechiseledBlockType DIRT_SQUARES = create("dirt_squares", "Dirt Squares").configure(DIRT_CONFIGURER).build();
    public static final RechiseledBlockType DIRT_TILES = create("dirt_tiles", "Dirt Tiles").configure(DIRT_CONFIGURER).build();
    public static final RechiseledBlockType DIRT_TILLED = create("dirt_tilled", "Tilled Dirt").configure(DIRT_CONFIGURER).build();
    // Emerald block
    private static final Supplier<BlockProperties> EMERALD_BLOCK_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.METAL, MaterialColor.EMERALD).requiresCorrectTool().destroyTime(5.0F).explosionResistance(6.0F).sound(SoundType.METAL);
    private static final Consumer<RechiseledBlockBuilder> EMERALD_BLOCK_CONFIGURER = b -> b.properties(EMERALD_BLOCK_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.EMERALD_BLOCK).recipe(BaseChiselingRecipes.EMERALD_BLOCK);
    public static final RechiseledBlockType EMERALD_BLOCK_BORDERED_CROSSES = create("emerald_block_bordered_crosses", "Bordered Emerald Crosses Block").configure(EMERALD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType EMERALD_BLOCK_BORDERED_PLATING = create("emerald_block_bordered_plating", "Bordered Emerald Plating Block").configure(EMERALD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType EMERALD_BLOCK_CHISELED = create("emerald_block_chiseled", "Chiseled Block of Emerald").configure(EMERALD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType EMERALD_BLOCK_CLOVERS = create("emerald_block_clovers", "Emerald Clovers Block").configure(EMERALD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType EMERALD_BLOCK_CROSSES = create("emerald_block_crosses", "Emerald Crosses Block").configure(EMERALD_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType EMERALD_BLOCK_CRYSTAL = create("emerald_block_crystal", "Emerald Crystal Block").configure(EMERALD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType EMERALD_BLOCK_PATTERNED = create("emerald_block_patterned", "Patterned Block of Emerald").configure(EMERALD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType EMERALD_BLOCK_PATTERNED_SQUARES = create("emerald_block_patterned_squares", "Patterned Emerald Squares Block").configure(EMERALD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType EMERALD_BLOCK_PILLAR = create("emerald_block_pillar", "Emerald Block Pillar").configure(EMERALD_BLOCK_CONFIGURER).specification(BlockSpecification.PILLAR).build();
    public static final RechiseledBlockType EMERALD_BLOCK_PLATING = create("emerald_block_plating", "Emerald Plating Block").configure(EMERALD_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType EMERALD_BLOCK_POLISHED = create("emerald_block_polished", "Polished Block of Emerald").configure(EMERALD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType EMERALD_BLOCK_SMOOTH = create("emerald_block_smooth", "Smooth Block of Emerald").configure(EMERALD_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType EMERALD_BLOCK_STRIPED = create("emerald_block_striped", "Striped Block of Emerald").configure(EMERALD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType EMERALD_BLOCK_WAXED = create("emerald_block_waxed", "Waxed Block of Emerald").configure(EMERALD_BLOCK_CONFIGURER).build();
    // End stone
    private static final Supplier<BlockProperties> END_STONE_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.SAND).requiresCorrectTool().destroyTime(3.0F).explosionResistance(9.0F);
    private static final Consumer<RechiseledBlockBuilder> END_STONE_CONFIGURER = b -> b.properties(END_STONE_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.END_STONE).recipe(BaseChiselingRecipes.END_STONE);
    public static final RechiseledBlockType END_STONE_BLOBS = create("end_stone_blobs", "End Stone Blobs").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_BRICK_PATTERN = create("end_stone_brick_pattern", "End Stone Brick Pattern").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_BRICK_PAVING = create("end_stone_brick_paving", "End Stone Brick Paving").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_CHISELED = create("end_stone_chiseled", "Chiseled End Stone").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_CRUSHED = create("end_stone_crushed", "Crushed End Stone").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_DIAGONAL_BRICKS = create("end_stone_diagonal_bricks", "Diagonal End Stone Bricks").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_MESH = create("end_stone_mesh", "End Stone Mesh").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_PAVING = create("end_stone_paving", "End Stone Paving").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_POLISHED = create("end_stone_polished", "Polished End Stone").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_ROTATED_BRICKS = create("end_stone_rotated_bricks", "Rotated End Stone Bricks").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_SCALES = create("end_stone_scales", "End Stone Scales").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_SMALL_TILES = create("end_stone_small_tiles", "Small End Stone Tiles").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_SPIRAL_PATTERN = create("end_stone_spiral_pattern", "Spiral End Stone Pattern").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_SQUARES = create("end_stone_squares", "End Stone Squares").configure(END_STONE_CONFIGURER).build();
    public static final RechiseledBlockType END_STONE_TILES = create("end_stone_tiles", "End Stone Tiles").configure(END_STONE_CONFIGURER).build();
    // Glowstone
    private static final Supplier<BlockProperties> GLOWSTONE_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.GLASS, MaterialColor.SAND).strength(0.3F).sound(SoundType.GLASS).lightLevel(p_50872_ -> 15);
    private static final Consumer<RechiseledBlockBuilder> GLOWSTONE_CONFIGURER = b -> b.properties(GLOWSTONE_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.GLOWSTONE).recipe(BaseChiselingRecipes.GLOWSTONE);
    public static final RechiseledBlockType GLOWSTONE_BRICK_PATTERN = create("glowstone_brick_pattern", "Glowstone Brick Pattern").configure(GLOWSTONE_CONFIGURER).build();
    public static final RechiseledBlockType GLOWSTONE_BRICK_PAVING = create("glowstone_brick_paving", "Glowstone Brick Paving").configure(GLOWSTONE_CONFIGURER).build();
    public static final RechiseledBlockType GLOWSTONE_BRICKS = create("glowstone_bricks", "Glowstone Bricks").configure(GLOWSTONE_CONFIGURER).build();
    public static final RechiseledBlockType GLOWSTONE_CRUSHED = create("glowstone_crushed", "Crushed Glowstone").configure(GLOWSTONE_CONFIGURER).build();
    public static final RechiseledBlockType GLOWSTONE_LARGE_TILES = create("glowstone_large_tiles", "Large Glowstone Tiles").configure(GLOWSTONE_CONFIGURER).build();
    public static final RechiseledBlockType GLOWSTONE_ROTATED_BRICKS = create("glowstone_rotated_bricks", "Rotated Glowstone Bricks").configure(GLOWSTONE_CONFIGURER).build();
    public static final RechiseledBlockType GLOWSTONE_SMALL_TILES = create("glowstone_small_tiles", "Small Glowstone Tiles").configure(GLOWSTONE_CONFIGURER).build();
    public static final RechiseledBlockType GLOWSTONE_SMOOTH = create("glowstone_smooth", "Smooth Glowstone").configure(GLOWSTONE_CONFIGURER).build();
    public static final RechiseledBlockType GLOWSTONE_TILES = create("glowstone_tiles", "Glowstone Tiles").configure(GLOWSTONE_CONFIGURER).build();
    // Gold block
    private static final Supplier<BlockProperties> GOLD_BLOCK_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.METAL, MaterialColor.GOLD).requiresCorrectTool().destroyTime(3.0F).explosionResistance(6.0F).sound(SoundType.METAL);
    private static final Consumer<RechiseledBlockBuilder> GOLD_BLOCK_CONFIGURER = b -> b.properties(GOLD_BLOCK_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.GOLD_BLOCK).recipe(BaseChiselingRecipes.GOLD_BLOCK);
    public static final RechiseledBlockType GOLD_BLOCK_BEAMS = create("gold_block_beams", "Gold Beams Block").configure(GOLD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType GOLD_BLOCK_BORDERED = create("gold_block_bordered", "Bordered Block of Gold").configure(GOLD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType GOLD_BLOCK_LINES = create("gold_block_lines", "Gold Lines Block").configure(GOLD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType GOLD_BLOCK_PATTERN = create("gold_block_pattern", "Gold Block Pattern").configure(GOLD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType GOLD_BLOCK_POLISHED = create("gold_block_polished", "Polished Block of Gold").configure(GOLD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType GOLD_BLOCK_SCALES = create("gold_block_scales", "Gold Scales Block").configure(GOLD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType GOLD_BLOCK_SMALL_BRICKS = create("gold_block_small_bricks", "Small Gold Bricks").configure(GOLD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType GOLD_BLOCK_SMALL_TILES = create("gold_block_small_tiles", "Small Gold Tiles").configure(GOLD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType GOLD_BLOCK_STRIPED = create("gold_block_striped", "Striped Block of Gold").configure(GOLD_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType GOLD_BLOCK_SMOOTH = create("gold_block_smooth", "Smooth Block of Gold").configure(GOLD_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType GOLD_BLOCK_TILES = create("gold_block_tiles", "Gold Tiles Block").configure(GOLD_BLOCK_CONFIGURER).build();
    // Granite
    private static final Supplier<BlockProperties> GRANITE_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.DIRT).requiresCorrectTool().destroyTime(1.5F).explosionResistance(6.0F);
    private static final Consumer<RechiseledBlockBuilder> GRANITE_CONFIGURER = b -> b.properties(GRANITE_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.POLISHED_GRANITE).recipe(BaseChiselingRecipes.GRANITE);
    public static final RechiseledBlockType GRANITE_BRICK_PATTERN = create("granite_brick_pattern", "Granite Brick Pattern").configure(GRANITE_CONFIGURER).build();
    public static final RechiseledBlockType GRANITE_BRICK_PAVING = create("granite_brick_paving", "Granite Brick Paving").configure(GRANITE_CONFIGURER).build();
    public static final RechiseledBlockType GRANITE_BRICKS = create("granite_bricks", "Granite Bricks").configure(GRANITE_CONFIGURER).build();
    public static final RechiseledBlockType GRANITE_DIAGONAL_BRICKS = create("granite_diagonal_bricks", "Diagonal Granite Bricks").configure(GRANITE_CONFIGURER).build();
    public static final RechiseledBlockType GRANITE_DOTTED = create("granite_dotted", "Dotted Granite").configure(GRANITE_CONFIGURER).build();
    public static final RechiseledBlockType GRANITE_PAVING = create("granite_paving", "Granite Paving").configure(GRANITE_CONFIGURER).build();
    public static final RechiseledBlockType GRANITE_POLISHED = create("granite_polished", "Polished Granite").configure(GRANITE_CONFIGURER).regularVariant(() -> Blocks.POLISHED_GRANITE).build();
    public static final RechiseledBlockType GRANITE_ROTATED_BRICKS = create("granite_rotated_bricks", "Rotated Granite Bricks").configure(GRANITE_CONFIGURER).build();
    public static final RechiseledBlockType GRANITE_SQUARES = create("granite_squares", "Granite Squares").configure(GRANITE_CONFIGURER).build();
    public static final RechiseledBlockType GRANITE_TILES = create("granite_tiles", "Granite Tiles").configure(GRANITE_CONFIGURER).build();
    public static final RechiseledBlockType GRANITE_WAVY = create("granite_wavy", "Wavy Granite").configure(GRANITE_CONFIGURER).build();
    // Iron block
    private static final Supplier<BlockProperties> IRON_BLOCK_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.METAL, MaterialColor.METAL).requiresCorrectTool().destroyTime(5.0F).explosionResistance(6.0F).sound(SoundType.METAL);
    private static final Consumer<RechiseledBlockBuilder> IRON_BLOCK_CONFIGURER = b -> b.properties(IRON_BLOCK_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.IRON_BLOCK).recipe(BaseChiselingRecipes.IRON_BLOCK);
    public static final RechiseledBlockType IRON_BLOCK_BORDERED = create("iron_block_bordered", "Bordered Block of Iron").configure(IRON_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType IRON_BLOCK_CHISELED = create("iron_block_chiseled", "Chiseled Block of Iron").configure(IRON_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType IRON_BLOCK_CONNECTING = create("iron_block_connecting", "Block of Iron").configure(IRON_BLOCK_CONFIGURER).regularVariant(() -> Blocks.IRON_BLOCK).build();
    public static final RechiseledBlockType IRON_BLOCK_FRAMED = create("iron_block_framed", "Framed Block of Iron").configure(IRON_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType IRON_BLOCK_GEARS = create("iron_block_gears", "Iron Gears Block").configure(IRON_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType IRON_BLOCK_LINES = create("iron_block_lines", "Iron Block Lines").configure(IRON_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType IRON_BLOCK_PATTERNED = create("iron_block_patterned", "Patterned Block of Iron").configure(IRON_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType IRON_BLOCK_PIPES = create("iron_block_pipes", "Iron Block Pipes").configure(IRON_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType IRON_BLOCK_PLATED = create("iron_block_plated", "Plated Block of Iron").configure(IRON_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType IRON_BLOCK_POLISHED = create("iron_block_polished", "Polished Block of Iron").configure(IRON_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType IRON_BLOCK_PROCESSED = create("iron_block_processed", "Processed Block of Iron").configure(IRON_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType IRON_BLOCK_PULVERIZED = create("iron_block_pulverized", "Pulverized Block of Iron").configure(IRON_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType IRON_BLOCK_REINFORCED = create("iron_block_reinforced", "Reinforced Block of Iron").configure(IRON_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType IRON_BLOCK_SHEETS = create("iron_block_sheets", "Block of Iron Sheets").configure(IRON_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType IRON_BLOCK_SMALL_BRICKS = create("iron_block_small_bricks", "Small Iron Block Tiles").configure(IRON_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType IRON_BLOCK_SMOOTH = create("iron_block_smooth", "Smooth Block of Iron").configure(IRON_BLOCK_CONFIGURER).noConnectingVariant().build();
    // Jungle planks
    private static final Supplier<BlockProperties> JUNGLE_PLANKS_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.WOOD, MaterialColor.DIRT).destroyTime(2.0F).explosionResistance(3.0F).sound(SoundType.WOOD);
    private static final Consumer<RechiseledBlockBuilder> JUNGLE_PLANKS_CONFIGURER = b -> b.properties(JUNGLE_PLANKS_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.JUNGLE_PLANKS).recipe(BaseChiselingRecipes.JUNGLE_PLANKS);
    public static final RechiseledBlockType JUNGLE_PLANKS_BEAMS = create("jungle_planks_beams", "Jungle Plank Beams").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_BRICK_PATTERN = create("jungle_planks_brick_pattern", "Jungle Plank Brick Pattern").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_BRICK_PAVING = create("jungle_planks_brick_paving", "Jungle Plank Brick Paving").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_BRICKS = create("jungle_planks_bricks", "Jungle Plank Bricks").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_CRATE = create("jungle_planks_crate", "Jungle Planks Crate").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_DIAGONAL_STRIPES = create("jungle_planks_diagonal_stripes", "Diagonal Jungle Plank Stripes").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_DIAGONAL_TILES = create("jungle_planks_diagonal_tiles", "Diagonal Jungle Plank Tiles").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_DOTTED = create("jungle_planks_dotted", "Dotted Jungle Planks").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_FLOORING = create("jungle_planks_flooring", "Jungle Plank Flooring").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_LARGE_TILES = create("jungle_planks_large_tiles", "Large Jungle Plank Tiles").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_MOSAIC = create("jungle_planks_mosaic", "Jungle Plank Mosaic").configure(JUNGLE_PLANKS_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType JUNGLE_PLANKS_PATTERN = create("jungle_planks_pattern", "Jungle Plank Pattern").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_ROTATED_BRICKS = create("jungle_planks_rotated_bricks", "Rotated Jungle Plank Bricks").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_SMALL_BRICKS = create("jungle_planks_small_bricks", "Small Jungle Plank Bricks").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_SMALL_TILES = create("jungle_planks_small_tiles", "Small Jungle Plank Tiles").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_SQUARES = create("jungle_planks_squares", "Jungle Plank Squares").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_TILES = create("jungle_planks_tiles", "Jungle Plank Tiles").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_WAVY = create("jungle_planks_wavy", "Wavy Jungle Planks").configure(JUNGLE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType JUNGLE_PLANKS_WOVEN = create("jungle_planks_woven", "Woven Jungle Planks").configure(JUNGLE_PLANKS_CONFIGURER).build();
    // Lapis block
    private static final Supplier<BlockProperties> LAPIS_BLOCK_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.METAL, MaterialColor.LAPIS).requiresCorrectTool().destroyTime(3.0F).explosionResistance(3.0F);
    private static final Consumer<RechiseledBlockBuilder> LAPIS_BLOCK_CONFIGURER = b -> b.properties(LAPIS_BLOCK_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.LAPIS_BLOCK).recipe(BaseChiselingRecipes.LAPIS_BLOCK);
    public static final RechiseledBlockType LAPIS_BLOCK_BORDERED = create("lapis_block_bordered", "Bordered Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType LAPIS_BLOCK_CHISELED = create("lapis_block_chiseled", "Chiseled Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType LAPIS_BLOCK_COBBLED = create("lapis_block_cobbled", "Cobbled Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType LAPIS_BLOCK_CONNECTING = create("lapis_block_connecting", "Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).regularVariant(() -> Blocks.LAPIS_BLOCK).build();
    public static final RechiseledBlockType LAPIS_BLOCK_CRUSHED = create("lapis_block_crushed", "Crushed Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType LAPIS_BLOCK_DECORATED = create("lapis_block_decorated", "Decorated Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType LAPIS_BLOCK_GLOSSY = create("lapis_block_glossy", "Glossy Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType LAPIS_BLOCK_INVERTED_TILES = create("lapis_block_inverted_tiles", "Inverted Lapis Lazuli Block Tiles").configure(LAPIS_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType LAPIS_BLOCK_MOSAIC = create("lapis_block_mosaic", "Mosaic Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType LAPIS_BLOCK_PATTERN = create("lapis_block_pattern", "Patterned Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType LAPIS_BLOCK_PILLAR = create("lapis_block_pillar", "Lapis Lazuli Block Pillar").configure(LAPIS_BLOCK_CONFIGURER).specification(BlockSpecification.PILLAR).build();
    public static final RechiseledBlockType LAPIS_BLOCK_POLISHED = create("lapis_block_polished", "Polished Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType LAPIS_BLOCK_SCALES = create("lapis_block_scales", "Lapis Lazuli Block Scales").configure(LAPIS_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType LAPIS_BLOCK_SMALL_TILES = create("lapis_block_small_tiles", "Small Lapis Lazuli Block Tiles").configure(LAPIS_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType LAPIS_BLOCK_SMOOTH = create("lapis_block_smooth", "Smooth Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType LAPIS_BLOCK_STRIPES = create("lapis_block_stripes", "Striped Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType LAPIS_BLOCK_SWIRLING = create("lapis_block_swirling", "Swirling Block of Lapis Lazuli").configure(LAPIS_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType LAPIS_BLOCK_TILES = create("lapis_block_tiles", "Lapis Lazuli Block Tiles").configure(LAPIS_BLOCK_CONFIGURER).build();
    // Mossy cobblestone
    private static final Supplier<BlockProperties> MOSSY_COBBLESTONE_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE).requiresCorrectTool().destroyTime(2.0F).explosionResistance(6.0F);
    private static final Consumer<RechiseledBlockBuilder> MOSSY_COBBLESTONE_CONFIGURER = b -> b.properties(MOSSY_COBBLESTONE_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.MOSSY_COBBLESTONE).recipe(BaseChiselingRecipes.COBBLESTONE);
    public static final RechiseledBlockType MOSSY_COBBLESTONE_BEAMS = create("mossy_cobblestone_beams", "Mossy Cobblestone Beams").configure(MOSSY_COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType MOSSY_COBBLESTONE_DENTED = create("mossy_cobblestone_dented", "Dented Mossy Cobblestone").configure(MOSSY_COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType MOSSY_COBBLESTONE_INVERTED_DENTED = create("mossy_cobblestone_inverted_dented", "Inverted Dented Mossy Cobblestone").configure(MOSSY_COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType MOSSY_COBBLESTONE_PAVING = create("mossy_cobblestone_paving", "Mossy Cobblestone Paving").configure(MOSSY_COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType MOSSY_COBBLESTONE_SMALL_TILES = create("mossy_cobblestone_small_tiles", "Small Mossy Cobblestone Tiles").configure(MOSSY_COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType MOSSY_COBBLESTONE_SQUARES = create("mossy_cobblestone_squares", "Mossy Cobblestone Squares").configure(MOSSY_COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType MOSSY_COBBLESTONE_STRIPES = create("mossy_cobblestone_stripes", "Mossy Cobblestone Stripes").configure(MOSSY_COBBLESTONE_CONFIGURER).build();
    public static final RechiseledBlockType MOSSY_COBBLESTONE_WORN_STRIPES = create("mossy_cobblestone_worn_stripes", "Weathered Mossy Cobblestone").configure(MOSSY_COBBLESTONE_CONFIGURER).build();
    // Netherrack
    private static final Supplier<BlockProperties> NETHERRACK_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.NETHER).requiresCorrectTool().strength(0.4F).sound(SoundType.NETHERRACK);
    private static final Consumer<RechiseledBlockBuilder> NETHERRACK_CONFIGURER = b -> b.properties(NETHERRACK_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.NETHERRACK).recipe(BaseChiselingRecipes.NETHERRACK);
    public static final RechiseledBlockType NETHERRACK_BEAMS = create("netherrack_beams", "Netherrack Beams").configure(NETHERRACK_CONFIGURER).build();
    public static final RechiseledBlockType NETHERRACK_BRICK_PATTERN = create("netherrack_brick_pattern", "Netherrack Brick Pattern").configure(NETHERRACK_CONFIGURER).build();
    public static final RechiseledBlockType NETHERRACK_BRICK_PAVING = create("netherrack_brick_paving", "Netherrack Brick Paving").configure(NETHERRACK_CONFIGURER).build();
    public static final RechiseledBlockType NETHERRACK_BRICKS = create("netherrack_bricks", "Netherrack Bricks").configure(NETHERRACK_CONFIGURER).build();
    public static final RechiseledBlockType NETHERRACK_DENTED = create("netherrack_dented", "Dented Netherrack").configure(NETHERRACK_CONFIGURER).build();
    public static final RechiseledBlockType NETHERRACK_ROTATED_BRICKS = create("netherrack_rotated_bricks", "Rotated Netherrack Bricks").configure(NETHERRACK_CONFIGURER).build();
    public static final RechiseledBlockType NETHERRACK_SMALL_TILES = create("netherrack_small_tiles", "Small Netherrack Tiles").configure(NETHERRACK_CONFIGURER).build();
    public static final RechiseledBlockType NETHERRACK_STRIPES = create("netherrack_stripes", "Netherrack Stripes").configure(NETHERRACK_CONFIGURER).build();
    public static final RechiseledBlockType NETHERRACK_TILES = create("netherrack_tiles", "Netherrack Tiles").configure(NETHERRACK_CONFIGURER).build();
    // Nether bricks
    private static final Supplier<BlockProperties> NETHER_BRICKS_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.NETHER).requiresCorrectTool().destroyTime(2.0F).explosionResistance(6.0F).sound(SoundType.NETHER_BRICKS);
    private static final Consumer<RechiseledBlockBuilder> NETHER_BRICKS_CONFIGURER = b -> b.properties(NETHER_BRICKS_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.NETHER_BRICKS).recipe(BaseChiselingRecipes.NETHER_BRICKS);
    public static final RechiseledBlockType NETHER_BRICKS_BEAMS = create("nether_bricks_beams", "Nether Brick Beams").configure(NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType NETHER_BRICKS_BRICK_PATTERN = create("nether_bricks_brick_pattern", "Nether Brick Pattern").configure(NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType NETHER_BRICKS_BRICK_PAVING = create("nether_bricks_brick_paving", "Nether Brick Paving").configure(NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType NETHER_BRICKS_CHISELED_SQUARES = create("nether_bricks_chiseled_squares", "Chiseled Nether Brick Squares").configure(NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType NETHER_BRICKS_DIAGONAL_BRICKS = create("nether_bricks_diagonal_bricks", "Diagonal Nether Bricks").configure(NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType NETHER_BRICKS_LARGE_BRICKS = create("nether_bricks_large_bricks", "Large Nether Bricks").configure(NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType NETHER_BRICKS_LARGE_TILES = create("nether_bricks_large_tiles", "Large Nether Brick Tiles").configure(NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType NETHER_BRICKS_ROTATED_BRICKS = create("nether_bricks_rotated_bricks", "Rotated Nether Bricks").configure(NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType NETHER_BRICKS_SMALL_TILES = create("nether_bricks_small_tiles", "Small Nether Brick Tiles").configure(NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType NETHER_BRICKS_SMOOTH = create("nether_bricks_smooth", "Nether Bricks Smooth").configure(NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType NETHER_BRICKS_SQUARES = create("nether_bricks_squares", "Nether Brick Squares").configure(NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType NETHER_BRICKS_TILES = create("nether_bricks_tiles", "Nether Brick Tiles").configure(NETHER_BRICKS_CONFIGURER).build();
    // Oak planks
    private static final Supplier<BlockProperties> OAK_PLANKS_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.WOOD, MaterialColor.WOOD).destroyTime(2.0F).explosionResistance(3.0F).sound(SoundType.WOOD);
    private static final Consumer<RechiseledBlockBuilder> OAK_PLANKS_CONFIGURER = b -> b.properties(OAK_PLANKS_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.OAK_PLANKS).recipe(BaseChiselingRecipes.OAK_PLANKS);
    public static final RechiseledBlockType OAK_PLANKS_BEAMS = create("oak_planks_beams", "Oak Plank Beams").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_BRICK_PATTERN = create("oak_planks_brick_pattern", "Oak Plank Brick Pattern").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_BRICK_PAVING = create("oak_planks_brick_paving", "Oak Plank Brick Paving").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_BRICKS = create("oak_planks_bricks", "Oak Plank Bricks").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_CRATE = create("oak_planks_crate", "Oak Planks Crate").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_DIAGONAL_STRIPES = create("oak_planks_diagonal_stripes", "Diagonal Oak Plank Stripes").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_DIAGONAL_TILES = create("oak_planks_diagonal_tiles", "Diagonal Oak Plank Tiles").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_DOTTED = create("oak_planks_dotted", "Dotted Oak Planks").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_FLOORING = create("oak_planks_flooring", "Oak Plank Flooring").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_LARGE_TILES = create("oak_planks_large_tiles", "Large Oak Plank Tiles").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_MOSAIC = create("oak_planks_mosaic", "Oak Plank Mosaic").configure(OAK_PLANKS_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType OAK_PLANKS_PATTERN = create("oak_planks_pattern", "Oak Plank Pattern").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_ROTATED_BRICKS = create("oak_planks_rotated_bricks", "Rotated Oak Plank Bricks").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_SMALL_BRICKS = create("oak_planks_small_bricks", "Small Oak Plank Bricks").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_SMALL_TILES = create("oak_planks_small_tiles", "Small Oak Plank Tiles").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_SQUARES = create("oak_planks_squares", "Oak Plank Squares").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_TILES = create("oak_planks_tiles", "Oak Plank Tiles").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_WAVY = create("oak_planks_wavy", "Wavy Oak Planks").configure(OAK_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType OAK_PLANKS_WOVEN = create("oak_planks_woven", "Woven Oak Planks").configure(OAK_PLANKS_CONFIGURER).build();
    // Obsidian
    private static final Supplier<BlockProperties> OBSIDIAN_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.COLOR_BLACK).requiresCorrectTool().destroyTime(50.0F).explosionResistance(1200.0F);
    private static final Consumer<RechiseledBlockBuilder> OBSIDIAN_CONFIGURER = b -> b.properties(OBSIDIAN_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.OBSIDIAN).recipe(BaseChiselingRecipes.OBSIDIAN);
    public static final RechiseledBlockType OBSIDIAN_BORDERED = create("obsidian_bordered", "Bordered Obsidian").configure(OBSIDIAN_CONFIGURER).build();
    public static final RechiseledBlockType OBSIDIAN_BRICK_PATTERN = create("obsidian_brick_pattern", "Obsidian Brick Pattern").configure(OBSIDIAN_CONFIGURER).build();
    public static final RechiseledBlockType OBSIDIAN_BRICK_PAVING = create("obsidian_brick_paving", "Obsidian Brick Paving").configure(OBSIDIAN_CONFIGURER).build();
    public static final RechiseledBlockType OBSIDIAN_BRICKS = create("obsidian_bricks", "Obsidian Bricks").configure(OBSIDIAN_CONFIGURER).build();
    public static final RechiseledBlockType OBSIDIAN_CHISELED = create("obsidian_chiseled", "Chiseled Obsidian").configure(OBSIDIAN_CONFIGURER).build();
    public static final RechiseledBlockType OBSIDIAN_CHISELED_CIRCLES = create("obsidian_chiseled_circles", "Chiseled Obsidian Circles").configure(OBSIDIAN_CONFIGURER).build();
    public static final RechiseledBlockType OBSIDIAN_CHISELED_CREEPER = create("obsidian_chiseled_creeper", "Chiseled Obsidian Creeper Face").configure(OBSIDIAN_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType OBSIDIAN_CHISELED_SKELETON = create("obsidian_chiseled_skeleton", "Chiseled Obsidian Skeleton Face").configure(OBSIDIAN_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType OBSIDIAN_DARK = create("obsidian_dark", "Dark Obsidian").configure(OBSIDIAN_CONFIGURER).build();
    public static final RechiseledBlockType OBSIDIAN_LARGE_TILES = create("obsidian_large_tiles", "Large Obsidian Tiles").configure(OBSIDIAN_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType OBSIDIAN_PILLARS = create("obsidian_pillars", "Obsidian Pillars").configure(OBSIDIAN_CONFIGURER).build();
    public static final RechiseledBlockType OBSIDIAN_ROTATED_BRICKS = create("obsidian_rotated_bricks", "Rotated Obsidian Bricks").configure(OBSIDIAN_CONFIGURER).build();
    public static final RechiseledBlockType OBSIDIAN_SPOTS = create("obsidian_spots", "Spotted Obsidian").configure(OBSIDIAN_CONFIGURER).build();
    public static final RechiseledBlockType OBSIDIAN_SQUARES = create("obsidian_squares", "Obsidian Squares").configure(OBSIDIAN_CONFIGURER).build();
    public static final RechiseledBlockType OBSIDIAN_STRIPES = create("obsidian_stripes", "Obsidian Stripes").configure(OBSIDIAN_CONFIGURER).build();
    public static final RechiseledBlockType OBSIDIAN_TILES = create("obsidian_tiles", "Obsidian Tiles").configure(OBSIDIAN_CONFIGURER).build();
    // Prismarine
    private static final Supplier<BlockProperties> PRISMARINE_BRICKS_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.DIAMOND).requiresCorrectTool().destroyTime(1.5F).explosionResistance(6.0F);
    private static final Consumer<RechiseledBlockBuilder> PRISMARINE_BRICKS_CONFIGURER = b -> b.properties(PRISMARINE_BRICKS_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.PRISMARINE_BRICKS).recipe(BaseChiselingRecipes.PRISMARINE_BRICKS);
    public static final RechiseledBlockType PRISMARINE_BRICKS_BEAMS = create("prismarine_bricks_beams", "Prismarine Brick Beams").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_BRICK_PATTERN = create("prismarine_bricks_brick_pattern", "Prismarine Brick Pattern").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_BRICK_PAVING = create("prismarine_bricks_brick_paving", "Prismarine Brick Paving").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_BRICKS = create("prismarine_bricks_bricks", "Prismarine Bricks").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_CHISELED_CIRCLES = create("prismarine_bricks_chiseled_circles", "Chiseled Prismarine Brick Circles").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_CHISELED_SQUARES = create("prismarine_bricks_chiseled_squares", "Chiseled Prismarine Brick Squares").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_DIAGONAL_BRICKS = create("prismarine_bricks_diagonal_bricks", "Diagonal Prismarine Bricks").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_DIAGONAL_TILES = create("prismarine_bricks_diagonal_tiles", "Diagonal Prismarine Brick Tiles").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_DOTTED = create("prismarine_bricks_dotted", "Dotted Prismarine Bricks").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_PILLARS = create("prismarine_bricks_pillars", "Prismarine Brick Pillars").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_POLISHED = create("prismarine_bricks_polished", "Polished Prismarine Bricks").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_ROTATED_BRICKS = create("prismarine_bricks_rotated_bricks", "Rotated Prismarine Bricks").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_ROWS = create("prismarine_bricks_rows", "Prismarine Brick Rows").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_SMALL_TILES = create("prismarine_bricks_small_tiles", "Small Prismarine Brick Tiles").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_SQUARES = create("prismarine_bricks_squares", "Prismarine Brick Squares").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_TILES = create("prismarine_bricks_tiles", "Prismarine Brick Tiles").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_WAVY = create("prismarine_bricks_wavy", "Wavy Prismarine Bricks").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType PRISMARINE_BRICKS_WOVEN = create("prismarine_bricks_woven", "Woven Prismarine Bricks").configure(PRISMARINE_BRICKS_CONFIGURER).build();
    // Purpur
    private static final Supplier<BlockProperties> PURPUR_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.COLOR_MAGENTA).requiresCorrectTool().destroyTime(1.5F).explosionResistance(6.0F);
    private static final Consumer<RechiseledBlockBuilder> PURPUR_CONFIGURER = b -> b.properties(PURPUR_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.PURPUR_BLOCK).recipe(BaseChiselingRecipes.PURPUR_BLOCK);
    public static final RechiseledBlockType PURPUR_BRICK_PATTERN = create("purpur_brick_pattern", "Purpur Brick Pattern").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_BRICK_PAVING = create("purpur_brick_paving", "Purpur Brick Paving").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_BRICKS = create("purpur_bricks", "Purpur Bricks").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_DIAGONAL_BRICKS = create("purpur_diagonal_bricks", "Diagonal Purpur Bricks").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_DIAGONAL_TILES = create("purpur_diagonal_tiles", "Diagonal Purpur Tiles").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_DOTTED = create("purpur_dotted", "Dotted Purpur Block").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_FABRIC = create("purpur_fabric", "Purpur Fabric").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_JAGGED_PATTERN = create("purpur_jagged_pattern", "Jagged Purpur Pattern").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_LARGE_TILES = create("purpur_large_tiles", "Large Purpur Tiles").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_ORGANIC_PATTERN = create("purpur_organic_pattern", "Organic Purpur Pattern").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_PILLAR = create("purpur_pillar", "Sided Purpur Pillar").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_ROTATED_BRICKS = create("purpur_rotated_bricks", "Rotated Purpur Bricks").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_SLANTED_TILES = create("purpur_slanted_tiles", "Slanted Purpur Tiles").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_SMALL_TILES = create("purpur_small_tiles", "Small Purpur Tiles").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_SPIRAL_PATTERN = create("purpur_spiral_pattern", "Spiral Purpur Pattern").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_SQUARES = create("purpur_squares", "Purpur Squares").configure(PURPUR_CONFIGURER).build();
    public static final RechiseledBlockType PURPUR_TILES = create("purpur_tiles", "Purpur Block").configure(PURPUR_CONFIGURER).regularVariant(() -> Blocks.PURPUR_BLOCK).build();
    public static final RechiseledBlockType PURPUR_WOVEN = create("purpur_woven", "Woven Purpur Block").configure(PURPUR_CONFIGURER).build();
    // Quartz block
    private static final Supplier<BlockProperties> QUARTZ_BLOCK_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.QUARTZ).requiresCorrectTool().strength(0.8F);
    private static final Consumer<RechiseledBlockBuilder> QUARTZ_BLOCK_CONFIGURER = b -> b.properties(QUARTZ_BLOCK_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.QUARTZ_BLOCK).recipe(BaseChiselingRecipes.QUARTZ_BLOCK);
    public static final RechiseledBlockType QUARTZ_BLOCK_BORDERED = create("quartz_block_bordered", "Bordered Quartz Block").configure(QUARTZ_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_BRICK_PAVING = create("quartz_block_brick_paving", "Quartz Brick Paving").configure(QUARTZ_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_CHISELED_PILLAR = create("quartz_block_chiseled_pillar", "Chiseled Quartz Pillar").configure(QUARTZ_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_CHISELED_SQUARES = create("quartz_block_chiseled_squares", "Chiseled Quartz Block Squares").configure(QUARTZ_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType QUARTZ_BLOCK_CONNECTING = create("quartz_block_connecting", "Quartz Block").configure(QUARTZ_BLOCK_CONFIGURER).regularVariant(() -> Blocks.QUARTZ_BLOCK).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_CROSSES = create("quartz_block_crosses", "Quartz Block Crosses").configure(QUARTZ_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_DIAGONAL_TILES = create("quartz_block_diagonal_tiles", "Diagonal Quartz Block Tiles").configure(QUARTZ_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_PATTERN = create("quartz_block_pattern", "Quartz Block Pattern").configure(QUARTZ_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_ROTATED_BRICKS = create("quartz_block_rotated_bricks", "Rotated Quartz Bricks").configure(QUARTZ_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_ROWS = create("quartz_block_rows", "Quartz Block Rows").configure(QUARTZ_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_SCALES = create("quartz_block_scales", "Quartz Block Scales").configure(QUARTZ_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_SMALL_TILES = create("quartz_block_small_tiles", "Small Quartz Block Tiles").configure(QUARTZ_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_SQUARES = create("quartz_block_squares", "Quartz Block Squares").configure(QUARTZ_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_STRIPES = create("quartz_block_stripes", "Quartz Block Stripes").configure(QUARTZ_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType QUARTZ_BLOCK_TILES = create("quartz_block_tiles", "Quartz Block Tiles").configure(QUARTZ_BLOCK_CONFIGURER).build();
    // Red nether bricks
    private static final Supplier<BlockProperties> RED_NETHER_BRICKS_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.NETHER).requiresCorrectTool().destroyTime(2.0F).explosionResistance(6.0F).sound(SoundType.NETHER_BRICKS);
    private static final Consumer<RechiseledBlockBuilder> RED_NETHER_BRICKS_CONFIGURER = b -> b.properties(RED_NETHER_BRICKS_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.RED_NETHER_BRICKS).recipe(BaseChiselingRecipes.RED_NETHER_BRICKS);
    public static final RechiseledBlockType RED_NETHER_BRICKS_BEAMS = create("red_nether_bricks_beams", "Red Nether Brick Beams").configure(RED_NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType RED_NETHER_BRICKS_BRICK_PATTERN = create("red_nether_bricks_brick_pattern", "Red Nether Brick Pattern").configure(RED_NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType RED_NETHER_BRICKS_BRICK_PAVING = create("red_nether_bricks_brick_paving", "Red Nether Brick Paving").configure(RED_NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType RED_NETHER_BRICKS_CHISELED_SQUARES = create("red_nether_bricks_chiseled_squares", "Chiseled Red Nether Brick Squares").configure(RED_NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType RED_NETHER_BRICKS_DIAGONAL_BRICKS = create("red_nether_bricks_diagonal_bricks", "Diagonal Red Nether Bricks").configure(RED_NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType RED_NETHER_BRICKS_LARGE_BRICKS = create("red_nether_bricks_large_bricks", "Large Red Nether Bricks").configure(RED_NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType RED_NETHER_BRICKS_LARGE_TILES = create("red_nether_bricks_large_tiles", "Large Red Nether Brick Tiles").configure(RED_NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType RED_NETHER_BRICKS_ROTATED_BRICKS = create("red_nether_bricks_rotated_bricks", "Rotated Red Nether Bricks").configure(RED_NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType RED_NETHER_BRICKS_SMALL_TILES = create("red_nether_bricks_small_tiles", "Small Red Nether Brick Tiles").configure(RED_NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType RED_NETHER_BRICKS_SMOOTH = create("red_nether_bricks_smooth", "Red Nether Bricks Smooth").configure(RED_NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType RED_NETHER_BRICKS_SQUARES = create("red_nether_bricks_squares", "Red Nether Brick Squares").configure(RED_NETHER_BRICKS_CONFIGURER).build();
    public static final RechiseledBlockType RED_NETHER_BRICKS_TILES = create("red_nether_bricks_tiles", "Red Nether Brick Tiles").configure(RED_NETHER_BRICKS_CONFIGURER).build();
    // Red sandstone
    private static final Supplier<BlockProperties> RED_SANDSTONE_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.COLOR_ORANGE).requiresCorrectTool().strength(0.8F);
    private static final Consumer<RechiseledBlockBuilder> RED_SANDSTONE_CONFIGURER = b -> b.properties(RED_SANDSTONE_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.RED_SANDSTONE).recipe(BaseChiselingRecipes.RED_SANDSTONE);
    public static final RechiseledBlockType RED_SANDSTONE_BRICK_PATTERN = create("red_sandstone_brick_pattern", "Red Sandstone Brick Pattern").configure(RED_SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType RED_SANDSTONE_BRICK_PAVING = create("red_sandstone_brick_paving", "Red Sandstone Brick Paving").configure(RED_SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType RED_SANDSTONE_BRICKS = create("red_sandstone_bricks", "Red Sandstone Bricks").configure(RED_SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType RED_SANDSTONE_DIAGONAL_BRICKS = create("red_sandstone_diagonal_bricks", "Diagonal Red Sandstone Bricks").configure(RED_SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType RED_SANDSTONE_LARGE_TILES = create("red_sandstone_large_tiles", "Large Red Sandstone Tiles").configure(RED_SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType RED_SANDSTONE_POLISHED = create("red_sandstone_polished", "Polished Red Sandstone").configure(RED_SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType RED_SANDSTONE_ROTATED_BRICKS = create("red_sandstone_rotated_bricks", "Rotated Red Sandstone Bricks").configure(RED_SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType RED_SANDSTONE_TILES = create("red_sandstone_tiles", "Red Sandstone Tiles").configure(RED_SANDSTONE_CONFIGURER).build();
    // Redstone block
    private static final Supplier<BlockProperties> REDSTONE_BLOCK_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.METAL, MaterialColor.FIRE).requiresCorrectTool().destroyTime(5.0F).explosionResistance(6.0F).sound(SoundType.METAL);
    private static final Consumer<RechiseledBlockBuilder> REDSTONE_BLOCK_CONFIGURER = b -> b.properties(REDSTONE_BLOCK_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.REDSTONE_BLOCK).recipe(BaseChiselingRecipes.REDSTONE_BLOCK);
    public static final RechiseledBlockType REDSTONE_BLOCK_BORDERED = create("redstone_block_bordered", "Bordered Block of Redstone").configure(REDSTONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType REDSTONE_BLOCK_BRICKS = create("redstone_block_bricks", "Redstone Block Bricks").configure(REDSTONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType REDSTONE_BLOCK_BRICK_BORDERED = create("redstone_block_brick_bordered", "Brick Bordered Block of Redstone").configure(REDSTONE_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType REDSTONE_BLOCK_CHISELED_CLOVERS = create("redstone_block_chiseled_clovers", "Chiseled Redstone Block Clovers").configure(REDSTONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType REDSTONE_BLOCK_CIRCLES = create("redstone_block_circles", "Redstone Block Circles").configure(REDSTONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType REDSTONE_BLOCK_COMPRESSED = create("redstone_block_compressed", "Compressed Block of Redstone").configure(REDSTONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType REDSTONE_BLOCK_CRUSHED = create("redstone_block_crushed", "Crushed Block of Redstone").configure(REDSTONE_BLOCK_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType REDSTONE_BLOCK_DIAGONAL_TILES = create("redstone_block_diagonal_tiles", "Diagonal Redstone Block Tiles").configure(REDSTONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType REDSTONE_BLOCK_PATTERNED = create("redstone_block_patterned", "Patterned Block of Redstone").configure(REDSTONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType REDSTONE_BLOCK_PAVING = create("redstone_block_paving", "Redstone Block Paving").configure(REDSTONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType REDSTONE_BLOCK_PILLAR = create("redstone_block_pillar", "Redstone Block Pillar").configure(REDSTONE_BLOCK_CONFIGURER).specification(BlockSpecification.PILLAR).build();
    public static final RechiseledBlockType REDSTONE_BLOCK_POLISHED = create("redstone_block_polished", "Polished Block of Redstone").configure(REDSTONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType REDSTONE_BLOCK_SCALES = create("redstone_block_scales", "Redstone Block Scales").configure(REDSTONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType REDSTONE_BLOCK_SMALL_TILES = create("redstone_block_small_tiles", "Small Redstone Block Tiles").configure(REDSTONE_BLOCK_CONFIGURER).build();
    public static final RechiseledBlockType REDSTONE_BLOCK_SMOOTH = create("redstone_block_smooth", "Smooth Block of Redstone").configure(REDSTONE_BLOCK_CONFIGURER).noConnectingVariant().build();
    // Sandstone
    private static final Supplier<BlockProperties> SANDSTONE_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.SAND).requiresCorrectTool().strength(0.8F);
    private static final Consumer<RechiseledBlockBuilder> SANDSTONE_CONFIGURER = b -> b.properties(SANDSTONE_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.SANDSTONE).recipe(BaseChiselingRecipes.SANDSTONE);
    public static final RechiseledBlockType SANDSTONE_BRICK_PATTERN = create("sandstone_brick_pattern", "Sandstone Brick Pattern").configure(SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType SANDSTONE_BRICK_PAVING = create("sandstone_brick_paving", "Sandstone Brick Paving").configure(SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType SANDSTONE_BRICKS = create("sandstone_bricks", "Sandstone Bricks").configure(SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType SANDSTONE_DIAGONAL_BRICKS = create("sandstone_diagonal_bricks", "Diagonal Sandstone Bricks").configure(SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType SANDSTONE_LARGE_TILES = create("sandstone_large_tiles", "Large Sandstone Tiles").configure(SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType SANDSTONE_POLISHED = create("sandstone_polished", "Polished Sandstone").configure(SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType SANDSTONE_ROTATED_BRICKS = create("sandstone_rotated_bricks", "Rotated Sandstone Bricks").configure(SANDSTONE_CONFIGURER).build();
    public static final RechiseledBlockType SANDSTONE_TILES = create("sandstone_tiles", "Sandstone Tiles").configure(SANDSTONE_CONFIGURER).build();
    // Spruce planks
    private static final Supplier<BlockProperties> SPRUCE_PLANKS_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.WOOD, MaterialColor.PODZOL).destroyTime(2.0F).explosionResistance(3.0F).sound(SoundType.WOOD);
    private static final Consumer<RechiseledBlockBuilder> SPRUCE_PLANKS_CONFIGURER = b -> b.properties(SPRUCE_PLANKS_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.SPRUCE_PLANKS).recipe(BaseChiselingRecipes.SPRUCE_PLANKS);
    public static final RechiseledBlockType SPRUCE_PLANKS_BEAMS = create("spruce_planks_beams", "Spruce Plank Beams").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_BRICK_PATTERN = create("spruce_planks_brick_pattern", "Spruce Plank Brick Pattern").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_BRICK_PAVING = create("spruce_planks_brick_paving", "Spruce Plank Brick Paving").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_BRICKS = create("spruce_planks_bricks", "Spruce Plank Bricks").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_CRATE = create("spruce_planks_crate", "Spruce Planks Crate").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_DIAGONAL_STRIPES = create("spruce_planks_diagonal_stripes", "Diagonal Spruce Plank Stripes").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_DIAGONAL_TILES = create("spruce_planks_diagonal_tiles", "Diagonal Spruce Plank Tiles").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_DOTTED = create("spruce_planks_dotted", "Dotted Spruce Planks").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_FLOORING = create("spruce_planks_flooring", "Spruce Plank Flooring").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_LARGE_TILES = create("spruce_planks_large_tiles", "Large Spruce Plank Tiles").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_MOSAIC = create("spruce_planks_mosaic", "Spruce Plank Mosaic").configure(SPRUCE_PLANKS_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType SPRUCE_PLANKS_PATTERN = create("spruce_planks_pattern", "Spruce Plank Pattern").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_ROTATED_BRICKS = create("spruce_planks_rotated_bricks", "Rotated Spruce Plank Bricks").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_SMALL_BRICKS = create("spruce_planks_small_bricks", "Small Spruce Plank Bricks").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_SMALL_TILES = create("spruce_planks_small_tiles", "Small Spruce Plank Tiles").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_SQUARES = create("spruce_planks_squares", "Spruce Plank Squares").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_TILES = create("spruce_planks_tiles", "Spruce Plank Tiles").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_WAVY = create("spruce_planks_wavy", "Wavy Spruce Planks").configure(SPRUCE_PLANKS_CONFIGURER).build();
    public static final RechiseledBlockType SPRUCE_PLANKS_WOVEN = create("spruce_planks_woven", "Woven Spruce Planks").configure(SPRUCE_PLANKS_CONFIGURER).build();
    // Stone
    private static final Supplier<BlockProperties> STONE_BLOCK_PROPERTIES = () -> BlockProperties.create(Material.STONE, MaterialColor.STONE).requiresCorrectTool().destroyTime(1.5F).explosionResistance(6.0F);
    private static final Consumer<RechiseledBlockBuilder> STONE_CONFIGURER = b -> b.properties(STONE_BLOCK_PROPERTIES).miningTagsFrom(() -> Blocks.STONE).recipe(BaseChiselingRecipes.STONE);
    public static final RechiseledBlockType STONE_BIG_TILES = create("stone_big_tiles", "Large Stone Tiles").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_BORDERED = create("stone_bordered", "Bordered Stone").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_BRICK_PATTERN = create("stone_brick_pattern", "Stone Brick Pattern").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_BRICK_PAVING = create("stone_brick_paving", "Stone Brick Paving").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_CHISELED_BRICKS = create("stone_chiseled_bricks", "Chiseled Stone Bricks").configure(STONE_CONFIGURER).regularVariant(() -> Blocks.CHISELED_STONE_BRICKS).build();
    public static final RechiseledBlockType STONE_COBBLED = create("stone_cobbled", "Cobbled Stone").configure(STONE_CONFIGURER).noConnectingVariant().build();
    public static final RechiseledBlockType STONE_CRUSHED = create("stone_crushed", "Crushed Stone").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_DIAGONAL_BRICKS = create("stone_diagonal_bricks", "Diagonal Stone Bricks").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_PATH = create("stone_path", "Stone Path").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_ROTATED_BRICKS = create("stone_rotated_bricks", "Rotated Stone Bricks").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_SLATED = create("stone_slated", "Slated Stone").configure(STONE_CONFIGURER).specification(BlockSpecification.PILLAR).noConnectingVariant().build();
    public static final RechiseledBlockType STONE_SMALL_BRICKS = create("stone_small_bricks", "Small Stone Bricks").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_SMALL_TILES = create("stone_small_tiles", "Small Stone Tiles").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_SMOOTH = create("stone_smooth", "Smooth Stone").configure(STONE_CONFIGURER).regularVariant(() -> Blocks.SMOOTH_STONE).build();
    public static final RechiseledBlockType STONE_SMOOTH_BRICK_PAVING = create("stone_smooth_brick_paving", "Smooth Stone Brick Paving").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_SMOOTH_LARGE_TILES = create("stone_smooth_large_tiles", "Large Smooth Stone Tiles").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_SMOOTH_ROTATED_BRICKS = create("stone_smooth_rotated_bricks", "Rotated Smooth Stone Bricks").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_SMOOTH_TILES = create("stone_smooth_tiles", "Smooth Stone Tiles").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_SQUARES = create("stone_squares", "Stone Squares").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_TILES = create("stone_tiles", "Stone Tiles").configure(STONE_CONFIGURER).build();
    public static final RechiseledBlockType STONE_WAVES = create("stone_waves", "Stone Waves").configure(STONE_CONFIGURER).build();

    private static RechiseledBlockBuilder create(String identifier, String translation){
        return Rechiseled.REGISTRATION.block(identifier).translation(translation);
    }

    public static void init(){
        // Cause this class to be initialized
    }
}
